### ISSUE TITLE
Getting 'std::logic_error' exception on running example in README.md

### ISSUE THREAD

**Issue by ibroheem** [acdemiralp/hid.hpp#3]
I get this when I run the example on the main page.

```
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string: construction from null is not valid

```

The debugger referenced the code [here](https://github.com/acdemiralp/hid.hpp/blob/b8980cd7c31c133f104d75c22b3a4191f0220d45/include/hid/hid.hpp#L258) as the issue: 
```
      result.emplace_back(
        iterator->path               ,
        iterator->vendor_id          ,
        iterator->product_id         ,
        iterator->serial_number      ,
        iterator->release_number     ,
        iterator->manufacturer_string,
        iterator->product_string     ,
        iterator->usage_page         ,
        iterator->usage              ,
        iterator->interface_number   ,
        static_cast<bus_type>(iterator->bus_type));

```

```
Ubuntu 23.10
hidapi: 0.14.0
hid.hpp: 0.14.0
```

Thanks

Edit: Never mind, it happens when default value 0 is in:
`enumerate  (const std::uint16_t vendor_id = 0, const std::uint16_t product_id = 0)`

**Comment by acdemiralp** [comment]
Hello the examples are just examples demonstrating usage, not tests, hence not guaranteed to run correctly on each machine. Enumeration returning an empty vector with vendor_id=0 (all vendors) and product_id=0 (all products) implies no HID devices are present on the machine.

Please re-open if this does not solve your issue.
